import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Section from "../components/Section";
import Services from "../components/Services";
import CaseStudies from "../components/CaseStudies";

import webDevIcon from "../public/img/web-dev-icon.svg";
import uxIcon from "../public/img/ux-icon.svg";
import appIcon from "../public/img/app-dev-icon.svg";
import blockchainIcon from "../public/img/blockchain-icon.svg";
import { getCaseStudies } from "../utils/kj-client";
import { Key } from "react";
import { CaseStudiesData } from "../utils/types";
import Clients from "../components/Clients";

interface iProps {
  caseStudies: CaseStudiesData[];
}

const servicesClass =
  "flex flex-col justify-start items-start col-span-12 xl:col-span-3 mt-14 mr-12";

const services = [
  {
    title: "Web development",
    icon: <Image src={webDevIcon} width={64} height={64} alt='' />,
    text: "We use cutting-edge web development technologies to help our clients fulfill their business goals through functional, reliable solutions.",
    className: servicesClass,
  },
  {
    title: "User experience & design",
    icon: <Image src={uxIcon} width={64} height={64} alt='' />,
    text: "Our complete web design services will bring your ideas to life and provide you with a sleek, high-performing product that elevates your business.",
    className: servicesClass,
  },
  {
    title: "Mobile app development",
    icon: <Image src={appIcon} width={64} height={64} alt='' />,
    text: "Our extensive mobile development experience allows us to create custom native and cross-platform iOS and Android mobile solutions for our clients.",
    className: servicesClass,
  },
  {
    title: "Blockchain solutions",
    icon: <Image src={blockchainIcon} width={64} height={64} alt='' />,
    text: "We conduct market research to determine the optimal blockchain-based solutions to help you grow your company and achieve your business goals.",
    className: servicesClass,
  },
];

export default function Home(props: iProps) {
  const { caseStudies } = props;
  console.log(caseStudies);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Banner />

      {/* What we do */}
      <Section
        heading='What we do'
        subHeading='We offer a complete range of bespoke design and development services to help you turn your ideas into digital masterpieces'
        className='max-w-9xl mx-auto w-full px-2 xl:px-0 py-20 flex flex-col justify-evenly items-start'
      >
        {services?.map((service) => (
          <Services
            key={service.title}
            icon={service.icon}
            title={service.title}
            text={service.text}
            className={service.className}
          />
        ))}
      </Section>

      {/* Case studies*/}
      {caseStudies && (
        <Section
          heading='Case studies'
          className='max-w-9xl mx-auto w-full py-20 flex flex-col justify-evenly items-start px-2 xl:px-0'
        >
          {caseStudies?.map((item) => (
            <CaseStudies
              key={item.title}
              className='relative py-[40%] col-span-12 xl:col-span-4 mb-5 xl:mb-0 xl:mr-10'
              image={item.imageUrl}
              title={item.title}
              description={item.description}
            />
          ))}
        </Section>
      )}

      <Section
        columns={0}
        heading='You’ll be in good company'
        subHeading='Trusted by leading brands'
        className='max-w-9xl mx-auto w-full py-20 flex flex-col justify-evenly items-start px-2 xl:px-0'
      >
        <Clients className='mt-10 mx-10 flex justify-center xl:justify-start flex-wrap' />
      </Section>
    </>
  );
}

export async function getStaticProps(context: any) {
  const data = await getCaseStudies();

  return {
    props: {
      caseStudies: data?.data,
    }, // will be passed to the page component as props
  };
}
